### ISSUE TITLE
installation on debian testing?

### ISSUE THREAD

**Issue by pazz** [jrollins/xapers#1]
I'm, trying to install this package from the master branch (github) on a current debian testing.
There seems to be an issue with the xapian dependency (python3-xapian) which is installed.

```
$  python3 ./setup.py install --user
...
Installing xapers script to /home/pazz/.local/bin

Installed /home/pazz/.local/lib/python3.6/site-packages/xapers-0.8-py3.6.egg
Processing dependencies for xapers==0.8
Searching for xapian
Reading https://pypi.python.org/simple/xapian/
Couldn't find index page for 'xapian' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for xapian
error: Could not find suitable distribution for Requirement.parse('xapian')
```

```
$ python3
Python 3.6.4+ (default, Feb 12 2018, 08:25:03) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xapian
>>> xapian
<module 'xapian' from '/usr/lib/python3/dist-packages/xapian/__init__.py'>
```

any ideas?

**Comment by jrollins** [comment]
Hi, Pazz.  First of all, if you're on debian you can actually just install xapers directly:
```
$ apt policy xapers
xapers:
  Installed: 0.8.2-1
  Candidate: 0.8.2-1
  Version table:
 *** 0.8.2-1 600
        600 https://deb.debian.org/debian testing/main amd64 Packages
        600 https://deb.debian.org/debian testing/main i386 Packages
        200 https://deb.debian.org/debian unstable/main amd64 Packages
        200 https://deb.debian.org/debian unstable/main i386 Packages
        100 /var/lib/dpkg/status
     0.7.1-1 500
        500 https://deb.debian.org/debian stable/main amd64 Packages
        500 https://deb.debian.org/debian stable/main i386 Packages
```
I maintain the debian packaging, so it's always up-to-date, and automatically pulls in all needed dependencies (including python3-xapian).

The xapian python bindings wrap the underlying C++ interface to xapian.  It looks like they're not available in pip.  But again, if you're on debian, you should just be able to install the python3-xapian package to pull in the dependency.

**Comment by jrollins** [comment]
Should also mention that the github repo was a bit out of date and I've updated it with the latest release.

**Comment by jrollins** [comment]
And to finally address your question, I have no idea why you're not finding xapian at runtime.  I assume it has to do with your environment when running from those local installs.  It seems to be not finding system-installed packages?  I don't ever run python packages from local installs like that, so I'm not sure what to suggest.  Make sure your PYTHONPATH is set properly?

xapers from the debian packaging certainly works though...

**Comment by pazz** [comment]
hi @jrollins thanks for the quick reply.
I was hoping to get a development version running and ultimately perhaps to land my ages-old patches that rewrite the parsers-code (to include postscript etc).
How do you develop then? Do you keep re-installing a system-wide installation?

**Comment by pazz** [comment]
I should say that `python3-xapian` is installed of course (the import works as expected).

**Comment by jrollins** [comment]
That would be great!

When testing I always just run right out of the source working directory:
```
servo:~/src/xapers/git [master] 141$ PYTHONPATH=lib python3 -m xapers --version
xapers 0.8.2
servo:~/src/xapers/git [master] 0$ 
```

I guess you're running into intricacies in how debian handles python packages.  Is setup.py installing in site-packages instead of dist-packages?

**Comment by pazz** [comment]
> Is setup.py installing in site-packages instead of dist-packages?
yes, I think so?

But this does not explain why `python3 setup.py` ultimately seems to fail to find the xapian lib, whereas `python3` does not. 

I'm also really confused about the PYTHONPATH behaviour:

```
$ PYTHONPATH=lib python3 -m xapers --version
```

works as expexted (as you do, in the xapers checkout). BUT:

```
PYTHONPATH=lib xapers --version 
Traceback (most recent call last): 
  File "/usr/local/bin/xapers", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xapian' distribution was not found and is required by xapers
```

I tried replacing the first line of `/usr/local/bin/xapers` from

```
#!/usr/bin/python3
```
to
```
#!/usr/bin/env python3
```

but this makes no difference.

**Comment by pazz** [comment]
Why does the system-wide version from the debian package work at all?!? It should fail for exactly the same reasons
